7-base_geometry.py
======================

>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry


    >>> mod_doc = __import__("7-base_geometry").__doc__
    >>> len(mod_doc) > 1
    True

    >>> base_doc = __import__("7-base_geometry").BaseGeometry.__doc__
    >>> len(base_doc) > 1
    True

    >>> area_doc = __import__("7-base_geometry").BaseGeometry.area.__doc__
    >>> len(area_doc) > 1
    True

    >>> valid_doc = __import__("7-base_geometry").BaseGeometry.integer_validator.__doc__
    >>> len(valid_doc) > 1
    True

=================
Tests (No errors)
=================

BaseGeometry takes no arguments:

    >>> bg = BaseGeometry()
    >>> bg.integer_validator('age', 5)

==============
Tests (Errors)
==============

    >>> new_bg = BaseGeometry(1)
    Traceback (most recent call last):
    TypeError: BaseGeometry() takes no arguments

The area method have to raise Exception:
    >>> bg.area()
    Traceback (most recent call last):
    Exception: area() is not implemented

    >>> bg.area(1)
    Traceback (most recent call last):
    TypeError: area() takes 1 positional argument but 2 were given

The integer_validator method: the value arg must be integer and greater than 0:

    >>> bg.integer_validator()
    Traceback (most recent call last):
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

    >>> bg.integer_validator('age')
    Traceback (most recent call last):
    TypeError: integer_validator() missing 1 required positional argument: 'value'

    >>> bg.integer_validator('age', '1')
    Traceback (most recent call last):
    TypeError: age must be an integer

    >>> bg.integer_validator('age', 33.66)
    Traceback (most recent call last):
    TypeError: age must be an integer

    >>> bg.integer_validator("boolean", True)
    Traceback (most recent call last):
    TypeError: boolean must be an integer

    >>> bg.integer_validator('age', 0)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

    >>> bg.integer_validator('age', -2)
    Traceback (most recent call last):
    ValueError: age must be greater than 0

    >>> bg.integer_validator('age', 1, 3, 4)
    Traceback (most recent call last):
    TypeError: integer_validator() takes 3 positional arguments but 5 were given
